In [2]:
import matplotlib.pyplot as plt
import scipy.linalg as sl
import autograd.numpy.linalg as la
import autograd.numpy as np
import sys
import os
from datetime import datetime
from matplotlib.collections import LineCollection

n_d = 22
NB = 83
netpath = '/Users/jiayiwu/experiment/bio/bio_network_2'
name = "/network_tri_num_p_%d_num_b_%d_fixed_" % (n_d, NB)
C = np.load(netpath + name + "Cde.npy")
points = np.load(netpath + name + "points.npy")
i_points = np.load(netpath + name + "i_points.npy")
connection = np.load(netpath + name + "Connection.npy")

# tri = Delaunay(points)
NB, dof = np.shape(C)
print(dof)

nums = [1, 2, 19, 20]

v1 = np.zeros(dof)

v1[nums[0] * 2:nums[0] * 2 + 4] = [1, 0, -1, 0]
v1[nums[2] * 2:nums[2] * 2 + 4] = [-1, 0, 1, 0]

indT1 = np.where(v1 > 0)[0]
indF1 = np.where(v1 < 0)[0]
zos1 = [nums[0] * 2 + 1, nums[0] * 2 + 3, nums[2] * 2 + 1, nums[2] * 2 + 3]

v1 = v1 / la.norm(v1)

v2 = np.zeros(dof)

v2[nums[0] * 2:nums[0] * 2 + 4] = [1, 0, -1, 0]
v2[nums[2] * 2:nums[2] * 2 + 4] = [1, 0, -1, 0]

indT2 = np.where(v2 > 0)[0]
indF2 = np.where(v2 < 0)[0]

v2 = v2 / la.norm(v2)


44


In [3]:
def ENE(fev1, indT, indF, zos):
    return thes * 4 - lthes * 4 + sum(-np.minimum(fev1[indT], thes)) + sum(np.maximum(fev1[indF], -thes)) + sum(
        np.maximum(abs(fev1[zos]), lthes))


def E12(k, sv):
    D = D_from_k(k, C)  # get the dynamic matrix
    e1, ev1 = sl.eigh(D)  # np.linalg.eig(D)  # get the eigval and eigvect

    seq = np.argsort(e1)  # sort the eigval

    if sv == 'v1':
        indT = indT1
        indF = indF1
    if sv == 'v2':
        indT = indT2
        indF = indF2

    zos = zos1

    return min(ENE(ev1[:, seq[0]], indT, indF, zos), ENE(-ev1[:, seq[0]], indT, indF, zos))


def fdiff_grad_eigvec(k, indT, indF, zos, w2=1.):
    D = D_from_k(k, C)  # get the dynamic matrix
    e1, ev1 = sl.eigh(D)  # get the eigval and eigvect

    seq = np.argsort(e1)  # sort the eigval

    fvec1 = min(ENE(ev1[:, seq[0]], indT, indF, zos), ENE(-ev1[:, seq[0]], indT, indF, zos))
    n1, n2 = np.sort(e1)[:2]
    dis1 = -np.arctan((n2 - n1) / gamma)

    dk1 = np.zeros(len(k))
    dk2 = np.zeros(len(k))

    dk = np.zeros(len(k))
    eps = 0.00001

    for i in range(len(k)):
        ki = k.copy()
        ki[i] += eps
        D2 = D_from_k(ki, C)
        e2, ev2 = sl.eigh(D2)

        seq = np.argsort(e2)

        fvec2 = min(ENE(ev2[:, seq[0]], indT, indF, zos), ENE(-ev2[:, seq[0]], indT, indF,
                                                              zos))
        dk[i] = (fvec2 - fvec1) / eps

        n1i, n2i = np.sort(e2)[:2]

        dk1[i] = (n1i - n1) / eps
        dk2[i] = (n2i - n2) / eps

    grad = dk - w2 * (1. / (((n2 - n1) / gamma) ** 2 + 1) * (dk2 - dk1))  # + eta * np.exp(-(k0 +1) * eta) * dk1s)
    cons_ene = dis1  # - eta * np.exp(-eta * (k0+1))

    return grad, fvec1, cons_ene


def grad_des(run_time, eps, k, indT, indF, zos, w2=1):
    energy = np.zeros(run_time)

    precision = 10 ** (-10)
    cons_ene = np.zeros(run_time)
    E1 = []
    for i in range(run_time):

        grad1, ene, cons = fdiff_grad_eigvec(k, indT, indF, zos, w2)
        # grad2 = grad(auto_energy)(k)
        gradient = grad1  # +grad2
        # gradient[abs(gradient)<np.argmax(abs(gradient))] =0

        gradient[gradient > 10] = 0

        gradient[gradient == np.nan] = 0
        # aa = np.where(gradient == max(gradient))

        k = k - eps * gradient
        # k[aa] = 0
        k[k < 0] = 0

        energy[i] = ene
        cons_ene[i] = cons
        E1.append([E12(k, 'v1'), E12(k, 'v2')])

        if i > 1 and la.norm(gradient) < precision:
            print('converaged at step=%d with ene %0.2f ' % (i, energy[i]))
            return k, np.array([energy[:i], cons_ene[:i]]), E1

    return k, np.array([energy, cons_ene]), E1


def D_from_k(k, A):
    return A.T @ np.diag(k) @ A


def plot_eig(k, v, fv, sep_datapath, name, indT, indF, ylim=1):
    D = D_from_k(k, C)

    eigval, eigvect = sl.eigh(D)
    seq = np.argsort((eigval))
    print('eigval are', np.round(eigval[seq], 3))
    plt.figure(figsize=(10, 6))

    plt.subplot(121)
    plt.plot(v, 'c--', alpha=0.8, linewidth=2, label='target')
    plt.scatter(range(0, len(v)), v[:len(v)])

    if ENE(eigvect[:, seq[0]], indT, indF, zos1) < ENE(-eigvect[:, seq[0]], indT, indF, zos1):
        fvec1 = eigvect[:, seq[0]]
    else:
        fvec1 = -eigvect[:, seq[0]]

    plt.plot(fvec1, 'r--')
    plt.scatter(fv, fvec1[fv], color='r')
    plt.title(str(name)[-2:] + ' at cycle: ' + str(name)[:len(str(name)) - 2], fontsize=20)
    plt.ylim(-0.4, 0.4)

    eig = np.sort(eigval)

    ax1 = plt.subplot(133)
    aa = np.reshape(np.repeat(eig, 2), (-1, 2))
    # print(aa)
    for i in range(10):
        plt.plot(aa[i], label=str(np.round(eig[i], 2)))

    plt.ylim(min(eigval) - 0.1, ylim + min(eigval) - 0.1)
    x_axis = ax1.axes.get_xaxis()
    x_axis.set_visible(False)
    plt.legend(bbox_to_anchor=(-0.6, 1.), loc=2, borderaxespad=0.)

    plt.savefig(sep_datapath + '/' + str(name) + '.png')
    # plt.show()
    plt.close()


def multiline(xs, ys, c, ax=None, **kwargs):
    """Plot lines with different colorings

    Parameters
    ----------
    xs : iterable container of x coordinates
    ys : iterable container of y coordinates
    c : iterable container of numbers mapped to colormap
    ax (optional): Axes to plot on.
    kwargs (optional): passed to LineCollection

    Notes:
        len(xs) == len(ys) == len(c) is the number of line segments
        len(xs[i]) == len(ys[i]) is the number of points for each line (indexed by i)

    Returns
    -------
    lc : LineCollection instance.
    """

    # find axes
    ax = plt.gca() if ax is None else ax

    # create LineCollection
    segments = [np.column_stack([x, y]) for x, y in zip(xs, ys)]
    lc = LineCollection(segments, **kwargs)

    # set coloring of line segments
    #    Note: I get an error if I pass c as a list here... not sure why.
    lc.set_array(np.asarray(c))

    # add lines to axes and rescale
    #    Note: adding a collection doesn't autoscalee xlim/ylim
    ax.add_collection(lc)
    ax.autoscale()
    return lc

def get_lines(xx,yy,NB=NB):
    xcon = []
    ycon = []
    for i in range(NB):

        if int(connection[i][0]) < len(xx):
            x0 = xx[int(connection[i][0])]
            y0 = yy[int(connection[i][0])]
        else:
            x0, y0 = points[int(connection[i][0])]
        if int(connection[i][1]) < len(xx):
            x1 = xx[int(connection[i][1])]
            y1 = yy[int(connection[i][1])]
        else:
            x1, y1 = points[int(connection[i][1])]

        xcon.append([x0, x1])
        ycon.append([y0, y1])

    xcon = np.array(xcon)
    ycon = np.array(ycon)
    return xcon, ycon
def plot_field(xx, yy,ip = i_points):
    plt.scatter(xx, yy, color='r', alpha=1)
    for i in range(len(ip)):
        if i in nums:
            alp = 0.9
            c = 'blue'
            hw = 12

        else:
            c = 'black'
            alp = 0.3
            hw = 8

        plt.annotate("", xytext=(ip[:, 0][i], ip[:, 1][i]), xy=(xx[i], yy[i]),
                     arrowprops=dict(width=1.5, headwidth=hw, color=c, alpha=alp))

   
    
def plot_act_net(points, ip, k, dirp, name, indT, indF, v, amp=1):
    long = (int(max(points[:, 0]) - min(points[:, 0]) + 4)) % 20
    wid = (int(max(points[:, 1]) - min(points[:, 1]) + 4)) % 20
    print(long, wid)
    fig = plt.figure(figsize=(long, wid))

    plt.plot(points[:, 0], points[:, 1], 'o', color='black', alpha=0.2)
    plt.plot(ip[:, 0], ip[:, 1], 'o', color='black', alpha=0.2)
    D = D_from_k(k, C)

    eigval, eigvect = sl.eigh(D)
    seq = np.argsort((eigval))
    xs = range(0, dof, 2)
    ys = range(1, dof + 1, 2)

    if ENE(eigvect[:, seq[0]], indT, indF, zos1) > ENE(-eigvect[:, seq[0]], indT, indF, zos1):
        fev1 = -eigvect[:, seq[0]]
        xx = -amp * eigvect[:, seq[0]][xs] + ip[:, 0]
        yy = -amp * eigvect[:, seq[0]][ys] + ip[:, 1]
    else:
        fev1 = eigvect[:, seq[0]]
        xx = amp * eigvect[:, seq[0]][xs] + ip[:, 0]
        yy = amp * eigvect[:, seq[0]][ys] + ip[:, 1]
    
    plot_field(xx, yy)
    for i in np.concatenate((indT, indF)):

        xi = points[:, 0][int(i / 2)]
        yi = points[:, 1][int(i / 2)]
        if yi > 1:
            jj = 0.5
        else:
            jj = -0.5
        plt.annotate("", xy=(xi + v[i], yi + jj), xytext=(xi, yi + jj),
                     arrowprops=dict(width=1.5, color='black', alpha=0.8))

    
    plt.axes().set_aspect('equal', 'datalim')
    xcon,ycon = get_lines(xx,yy)

    elongation = C @ fev1
    lc = multiline(xcon, ycon, elongation, cmap='plasma', lw=2, alpha=0.7)
    axcb = fig.colorbar(lc)
    axcb.set_label('bond elongation ')

    plt.ylim(min(points[:, 1]) - 0.5, max(points[:, 1]) + 0.5)
    plt.xlim(min(points[:, 0]) - 0.5, max(points[:, 0]) + 0.5)
    plt.axis('off')
    plt.title(str(name)[-2:] + ' at: ' + str(name)[:len(str(name)) - 2] +
              ' eigval = %0.2f with amplify :%d' % (eigval[seq[0]], amp), fontsize=20)
    plt.savefig(dirp + '/network_' + str(name) + '.pdf')
    print(eigval[seq][:5])
    plt.close()
    # plt.show()
    
    fig = plt.figure(figsize=(long, wid))
    plot_field(xx, yy)
    xcon,ycon = get_lines(ip[:,0],ip[:,1])
    lc = multiline(xcon, ycon, k, cmap='coolwarm', lw=2, alpha=1)
    axcb = fig.colorbar(lc)
    axcb.set_label('k')
    plt.axes().set_aspect('equal', 'datalim')

    plt.ylim(min(points[:, 1]) - 0.5, max(points[:, 1]) + 0.5)
    plt.xlim(min(points[:, 0]) - 0.5, max(points[:, 0]) + 0.5)
    plt.axis('off')
    plt.title(str(name)[-2:] + ' at: ' + str(name)[:len(str(name)) - 2] +
              ' eigval = %0.2f with amplify :%d' % (eigval[seq[0]], amp), fontsize=20)
    plt.savefig(dirp + '/k_network_' + str(name) + '.pdf')

    plt.close()

    # ake another one for k
    


def osc_goals(k, it, T, plotit=True, j=0):
    dif_ene = []
    dif_bond = []
    E1 = []
    plt.clf()
    plt.close()
    c_t_1 = []
    c_t_2 = []
    i = 0

    while i < T:

        k, energy1, E11 = grad_des(it, eps, k, indT2, indF2, zos1)
        plot_eig(k, v2, np.where(v2 != 0)[0], opath, '%02dv2' % i, indT2, indF2)
        plot_act_net(points, i_points, k, opath, '%02dv2' % i, indT2, indF2, v2)
        print(i)

        prev_k = k.copy()

        Ev2 = np.array(E11).T[1]
        E1 += E11

        if Ev2[-1] < precision:
            c_t_2 += [np.amin(np.where(Ev2 < precision)) / it]

        else:
            c_t_2 += [1]
        # print('end ene for v2 is', Ev2[-1])

        k, energy1, E11 = grad_des(it, eps, k, indT1, indF1, zos1)
        E1 += E11

        Ev1 = np.array(E11).T[0]
        # print('end ene for v1 is', Ev1[-1])

        if Ev1[-1] < precision:
            c_t_1 += [np.amin(np.where(Ev1 < precision)) / it]

        else:
            c_t_1 += [1]

        dif_ene += [la.norm(prev_k - k, 1)]
        diff = prev_k - k
        # print(diff)

        diff[abs(diff) < 0.5 * k] = 0

        dif_bond += [np.count_nonzero(diff)]
        plot_eig(k, v1, np.where(v1 != 0)[0], opath, '%02dv1' % i, indT1, indF1)
        plot_act_net(points, i_points, k, opath, '%02dv1' % i, indT1, indF1, v1)

        if c_t_1[-1] != 1 and c_t_2[-1] != 1:
            flag = True
            print('osc coveraged at', i)
            break
        

        

        i += 1

    if c_t_1[-1] == 1 or c_t_2[-1] == 1:

        flag = False
        print('osc didnt coverage')


        # return dif_bond, dif_ene, flag
    else:
        bondnum = np.where(abs(diff) > 0.5 * k)
        flag = True
        np.save(tpath + '/%02dv1_%d' % (j, T), prev_k)
        np.save(tpath + '/%02dv2_%d' % (j, T), k)
        np.save(tpath + '/%02d_bond_nums' % j, bondnum)

    if plotit:
        plt.clf()
        plt.close()
        plt.plot(c_t_1, label='v1 converage time')
        plt.plot(c_t_2, label='v2 converage time')
        plt.legend()
        # plt.xlim(0,20)
        plt.ylabel('converage time', fontsize=20)
        plt.xlabel('cycles', fontsize=20)
        plt.savefig(dirpath + '/T_%d_rt_%d_converage_time_%04d.png' % (T, it, j), dpi=100,
                    bbox_inches='tight')
        plt.close()
        # from mpl_toolkits.axes_grid.inset_locator import inset_axes

        fig = plt.figure(figsize=(7, 6))
        ax = fig.add_subplot(111)
        Ear = np.array(E1)

        # nn = 1  # np.max([int(it / 100), 1])

        ax.plot(np.arange(len(Ear.T[0])), Ear.T[0], label='G1')  # , s = 0.01)
        ax.plot(np.arange(len(Ear.T[1])), Ear.T[1], label='G2')
        # plt.plot(range(len(Ear.T[2])),Ear.T[2], label = 'E3 (Av3) changing over time')
        ax.set_ylabel('Energy changing over time')
        ax.set_xlabel('real time')
        fig.legend(bbox_to_anchor=(0.5, 0.55), loc=2, borderaxespad=0.)

        plt.ylim(ymin=0)

        plt.savefig(dirpath + '/T_%04d_rt_%d_Ene_A1_%04d.pdf' % (T, it, j), dpi=100)
        plt.close()
        # if flag:
        #    plot_eig(k, v1, np.where(v1 != 0)[0], tpath, '%02dv1' % j, indT1, indF1)
        #    plot_act_net(points, i_points, k, tpath, '%02dv1' % j, indT1, indF1, v1)

    #             plot_eig(prev_k, v2, np.where(v2 != 0)[0], tpath, '%02dv2' % j, indT2, indF2)
    #             plot_act_net(points, i_points, prev_k, tpath, '%02dv2' % j, indT2, indF2, v2)

    return dif_ene, dif_bond, flag

In [4]:
Kall = np.load('/Users/jiayiwu/experiment/bio/bio_mec_s/ks_it_1000_500.npy')

In [8]:
thes = 0.1
lthes = 0.05

gamma = 0.05  # making n2-n1 big
# eta = 0.5
precision = 0.05
eps = 0.1

run_time = 10000
it = int(run_time/T)
ori_k = Kall[i]




dif_ene_3, dif_bond, flag = osc_goals(ori_k, it, T, True, i)


eigval are [0.094 0.174 0.212 0.278 0.311 0.349 0.41  0.484 0.587 0.646 0.676 0.706
 0.809 0.817 0.861 0.905 0.948 1.052 1.12  1.138 1.183 1.299 1.315 1.489
 1.528 1.534 1.573 1.839 1.872 1.974 2.043 2.156 2.168 2.262 2.384 2.45
 2.57  2.721 2.88  3.19  3.325 3.406 3.568 3.716]
10 9


/Users/jiayiwu/anaconda/envs/bio/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py:107: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  warnings.warn(message, mplDeprecation, stacklevel=1)


[0.09426758 0.17403453 0.21237012 0.27769688 0.31058416]
0
eigval are [0.073 0.175 0.208 0.275 0.3   0.337 0.445 0.504 0.601 0.655 0.674 0.708
 0.805 0.825 0.847 0.885 0.951 1.049 1.125 1.135 1.187 1.314 1.373 1.493
 1.538 1.544 1.587 1.84  1.887 1.987 2.058 2.18  2.21  2.275 2.389 2.445
 2.584 2.739 2.89  3.19  3.296 3.407 3.583 3.68 ]
10 9
[0.07252595 0.1745686  0.2083266  0.27518286 0.30011899]
eigval are [0.061 0.169 0.21  0.276 0.302 0.322 0.428 0.483 0.599 0.645 0.658 0.713
 0.807 0.818 0.846 0.896 0.956 1.059 1.134 1.136 1.2   1.321 1.379 1.502
 1.535 1.55  1.587 1.841 1.887 2.003 2.07  2.192 2.226 2.285 2.397 2.438
 2.607 2.751 2.91  3.2   3.308 3.408 3.601 3.686]
10 9
[0.06072365 0.1690226  0.20969991 0.27632126 0.30182655]
1
eigval are [0.079 0.194 0.208 0.285 0.307 0.359 0.457 0.516 0.615 0.648 0.668 0.713
 0.76  0.831 0.857 0.911 0.96  1.069 1.13  1.143 1.214 1.331 1.421 1.511
 1.541 1.566 1.604 1.827 1.901 2.008 2.079 2.205 2.259 2.304 2.404 2.453
 2.616 2.771 2.925 3.183 

[0.1551991  0.26707594 0.2787743  0.33643357 0.37902635]
12
eigval are [0.156 0.272 0.273 0.339 0.393 0.484 0.522 0.586 0.612 0.687 0.727 0.765
 0.827 0.869 0.976 1.019 1.054 1.143 1.264 1.283 1.328 1.373 1.475 1.585
 1.705 1.797 1.845 1.952 2.092 2.259 2.379 2.428 2.548 2.605 2.73  2.799
 2.937 3.017 3.177 3.249 3.499 3.648 3.914 4.203]
10 9
[0.15646946 0.27186444 0.27332424 0.33938528 0.39326179]
eigval are [0.153 0.278 0.281 0.352 0.387 0.494 0.516 0.597 0.627 0.714 0.755 0.781
 0.832 0.891 0.97  1.021 1.028 1.157 1.272 1.302 1.329 1.378 1.473 1.594
 1.718 1.815 1.854 1.962 2.109 2.252 2.393 2.433 2.563 2.604 2.74  2.808
 2.941 3.021 3.155 3.254 3.499 3.646 3.931 4.232]
10 9
[0.15278419 0.27752983 0.28098369 0.35197678 0.38727431]
13
eigval are [0.152 0.274 0.276 0.343 0.4   0.487 0.518 0.589 0.614 0.69  0.731 0.768
 0.829 0.875 0.987 1.029 1.043 1.15  1.275 1.293 1.336 1.38  1.477 1.597
 1.716 1.81  1.857 1.966 2.106 2.274 2.398 2.439 2.564 2.619 2.742 2.808
 2.959 3.038 3.199 3.26

[0.14309946 0.30190876 0.30425282 0.38377337 0.43090939]
24
eigval are [0.144 0.3   0.302 0.379 0.441 0.502 0.529 0.619 0.649 0.698 0.775 0.788
 0.863 0.89  1.022 1.036 1.126 1.207 1.346 1.364 1.422 1.45  1.518 1.671
 1.796 1.892 1.976 2.07  2.199 2.383 2.512 2.585 2.668 2.779 2.827 2.939
 3.105 3.22  3.328 3.499 3.808 3.869 4.244 4.658]
10 9
[0.14362661 0.29985876 0.30188981 0.37944141 0.44118636]
eigval are [0.144 0.306 0.307 0.39  0.435 0.507 0.543 0.649 0.679 0.75  0.766 0.82
 0.869 0.923 1.007 1.029 1.129 1.223 1.37  1.372 1.424 1.459 1.516 1.675
 1.807 1.906 1.976 2.081 2.207 2.384 2.521 2.59  2.667 2.786 2.835 2.968
 3.111 3.225 3.297 3.494 3.806 3.868 4.265 4.684]
10 9
[0.14385317 0.30556746 0.30725978 0.39045232 0.4349755 ]
25
eigval are [0.145 0.303 0.305 0.385 0.443 0.506 0.532 0.618 0.654 0.701 0.778 0.797
 0.865 0.895 1.024 1.036 1.138 1.213 1.348 1.37  1.43  1.455 1.522 1.675
 1.802 1.899 1.986 2.078 2.208 2.389 2.519 2.6   2.676 2.793 2.833 2.952
 3.116 3.236 3.335 3.519

[0.14205929 0.31692205 0.32300428 0.40173618 0.46318982]
36
eigval are [0.142 0.32  0.322 0.407 0.464 0.517 0.544 0.634 0.68  0.723 0.795 0.837
 0.883 0.921 1.021 1.064 1.204 1.263 1.388 1.413 1.494 1.524 1.561 1.725
 1.865 1.956 2.073 2.159 2.263 2.448 2.579 2.719 2.745 2.893 2.92  3.08
 3.229 3.336 3.441 3.725 4.043 4.09  4.506 5.017]
10 9
[0.14244703 0.31968565 0.32158556 0.40681287 0.46380482]
eigval are [0.141 0.319 0.324 0.403 0.465 0.518 0.564 0.671 0.712 0.765 0.793 0.859
 0.901 0.946 0.98  1.056 1.206 1.275 1.414 1.419 1.495 1.534 1.554 1.726
 1.877 1.969 2.067 2.169 2.266 2.452 2.585 2.713 2.745 2.898 2.938 3.107
 3.233 3.316 3.433 3.71  4.04  4.092 4.528 5.041]
10 9
[0.14140118 0.31921395 0.323582   0.40292437 0.46477095]
37
eigval are [0.14  0.315 0.321 0.398 0.466 0.514 0.543 0.637 0.677 0.717 0.794 0.835
 0.883 0.919 1.012 1.068 1.206 1.264 1.392 1.415 1.498 1.528 1.564 1.729
 1.871 1.959 2.079 2.167 2.265 2.453 2.583 2.722 2.749 2.899 2.928 3.086
 3.238 3.341 3.452 3.742

[0.14397438 0.3321258  0.33841298 0.41929574 0.49263921]
48
eigval are [0.142 0.334 0.336 0.422 0.487 0.53  0.559 0.662 0.702 0.742 0.815 0.871
 0.904 0.948 1.024 1.094 1.25  1.309 1.422 1.449 1.546 1.578 1.619 1.771
 1.927 2.01  2.15  2.241 2.309 2.503 2.631 2.785 2.827 2.978 3.012 3.201
 3.346 3.404 3.573 3.903 4.243 4.308 4.735 5.325]
10 9
[0.14249796 0.33367423 0.33565951 0.42210452 0.48705248]
eigval are [0.144 0.339 0.34  0.429 0.496 0.531 0.585 0.696 0.744 0.786 0.821 0.894
 0.931 0.973 0.995 1.087 1.257 1.323 1.446 1.46  1.551 1.577 1.622 1.772
 1.939 2.027 2.139 2.249 2.316 2.507 2.638 2.78  2.829 2.99  3.03  3.234
 3.348 3.382 3.571 3.885 4.242 4.31  4.751 5.345]
10 9
[0.14351532 0.33945472 0.33962653 0.42910006 0.49616825]
49
eigval are [0.141 0.33  0.336 0.416 0.487 0.529 0.558 0.662 0.7   0.739 0.815 0.872
 0.903 0.948 1.015 1.095 1.253 1.312 1.424 1.452 1.549 1.582 1.625 1.774
 1.932 2.014 2.155 2.246 2.313 2.507 2.635 2.789 2.831 2.984 3.018 3.207
 3.355 3.409 3.586 3.91

[0.14417193 0.34426867 0.35197154 0.43483833 0.51638434]
60
eigval are [0.142 0.346 0.349 0.437 0.502 0.544 0.572 0.68  0.72  0.765 0.835 0.899
 0.924 0.974 1.028 1.114 1.288 1.353 1.447 1.483 1.584 1.615 1.688 1.809
 1.979 2.059 2.209 2.307 2.363 2.553 2.677 2.836 2.889 3.069 3.088 3.3
 3.435 3.486 3.707 4.048 4.424 4.501 4.927 5.584]
10 9
[0.14187949 0.34603548 0.34872829 0.43654152 0.5016739 ]
eigval are [0.144 0.353 0.353 0.446 0.52  0.544 0.603 0.715 0.771 0.803 0.846 0.923
 0.958 0.998 1.    1.111 1.297 1.366 1.469 1.496 1.591 1.61  1.693 1.812
 1.993 2.078 2.197 2.312 2.374 2.557 2.683 2.831 2.891 3.085 3.106 3.334
 3.42  3.48  3.705 4.029 4.425 4.502 4.941 5.603]
10 9
[0.14409524 0.35282372 0.35297228 0.44565836 0.52037577]
61
eigval are [0.142 0.35  0.35  0.442 0.503 0.544 0.572 0.681 0.722 0.77  0.836 0.902
 0.928 0.976 1.034 1.116 1.291 1.355 1.449 1.486 1.587 1.618 1.694 1.812
 1.984 2.064 2.213 2.312 2.368 2.557 2.681 2.84  2.893 3.077 3.094 3.308
 3.441 3.494 3.718 4.059 

[0.15012496 0.36592608 0.36662591 0.46452417 0.54315341]
72
eigval are [0.145 0.359 0.362 0.451 0.518 0.558 0.588 0.7   0.737 0.788 0.858 0.929
 0.945 0.998 1.035 1.14  1.32  1.385 1.469 1.515 1.616 1.65  1.75  1.848
 2.027 2.106 2.259 2.354 2.429 2.605 2.721 2.884 2.937 3.154 3.161 3.393
 3.496 3.587 3.837 4.177 4.587 4.675 5.097 5.813]
10 9
[0.14508982 0.35894326 0.36150041 0.45129122 0.51752857]
eigval are [0.149 0.366 0.367 0.461 0.542 0.562 0.622 0.733 0.795 0.825 0.872 0.951
 0.983 0.998 1.028 1.139 1.33  1.4   1.49  1.529 1.62  1.65  1.756 1.852
 2.04  2.127 2.246 2.355 2.442 2.608 2.728 2.881 2.939 3.173 3.178 3.425
 3.482 3.587 3.834 4.159 4.588 4.675 5.11  5.832]
10 9
[0.14934229 0.36559438 0.36664537 0.46128031 0.54237227]
73
eigval are [0.145 0.363 0.364 0.458 0.519 0.558 0.587 0.701 0.739 0.795 0.859 0.931
 0.951 1.001 1.039 1.142 1.322 1.388 1.471 1.518 1.618 1.652 1.754 1.851
 2.031 2.11  2.262 2.357 2.434 2.608 2.725 2.888 2.939 3.16  3.169 3.4
 3.501 3.596 3.848 4.187 

[0.15263108 0.37704191 0.377942   0.47476726 0.55780485]
84
eigval are [0.144 0.368 0.372 0.459 0.528 0.567 0.594 0.715 0.752 0.806 0.875 0.954
 0.965 1.014 1.041 1.161 1.348 1.415 1.488 1.544 1.639 1.683 1.802 1.884
 2.07  2.147 2.3   2.388 2.497 2.654 2.762 2.925 2.975 3.222 3.237 3.466
 3.552 3.687 3.961 4.294 4.726 4.833 5.247 6.019]
10 9
[0.1444839  0.36838452 0.37240964 0.45916384 0.52802861]
eigval are [0.153 0.378 0.379 0.478 0.56  0.578 0.638 0.749 0.821 0.845 0.894 0.976
 1.001 1.016 1.052 1.164 1.358 1.427 1.509 1.559 1.642 1.689 1.808 1.891
 2.083 2.172 2.287 2.39  2.51  2.657 2.769 2.925 2.978 3.237 3.261 3.498
 3.552 3.688 3.958 4.277 4.733 4.835 5.262 6.038]
10 9
[0.15343267 0.37797684 0.37948907 0.47796806 0.56017899]
85
eigval are [0.148 0.373 0.375 0.47  0.531 0.573 0.601 0.719 0.754 0.815 0.882 0.957
 0.969 1.019 1.051 1.165 1.349 1.415 1.49  1.548 1.644 1.687 1.805 1.888
 2.073 2.153 2.304 2.392 2.502 2.659 2.766 2.931 2.98  3.226 3.247 3.485
 3.558 3.694 3.971 4.30

[0.15610637 0.38807753 0.38851225 0.48587095 0.56932036]
96
eigval are [0.148 0.382 0.384 0.476 0.541 0.583 0.607 0.734 0.767 0.829 0.896 0.978
 0.988 1.028 1.063 1.188 1.374 1.441 1.507 1.573 1.663 1.718 1.845 1.923
 2.111 2.189 2.338 2.422 2.562 2.705 2.802 2.964 3.017 3.284 3.314 3.547
 3.614 3.781 4.081 4.403 4.86  4.987 5.388 6.212]
10 9
[0.1482197  0.38238266 0.38373223 0.47563091 0.54133363]
eigval are [0.157 0.389 0.39  0.488 0.571 0.597 0.653 0.764 0.837 0.864 0.917 0.996
 1.005 1.037 1.077 1.189 1.386 1.455 1.527 1.587 1.663 1.727 1.852 1.93
 2.125 2.214 2.325 2.422 2.575 2.707 2.809 2.965 3.02  3.298 3.338 3.561
 3.63  3.783 4.078 4.387 4.866 4.987 5.401 6.229]
10 9
[0.15699947 0.38923409 0.38982751 0.48753432 0.5707276 ]
97
eigval are [0.148 0.381 0.384 0.473 0.541 0.584 0.606 0.735 0.768 0.828 0.897 0.979
 0.989 1.025 1.063 1.19  1.376 1.443 1.509 1.575 1.664 1.721 1.848 1.927
 2.115 2.192 2.341 2.424 2.567 2.71  2.806 2.966 3.021 3.289 3.319 3.551
 3.62  3.789 4.09  4.412

[0.1600251  0.39912737 0.39949601 0.49916339 0.58217171]
108
eigval are [0.152 0.393 0.394 0.487 0.552 0.598 0.62  0.75  0.782 0.849 0.915 0.997
 1.007 1.041 1.084 1.212 1.397 1.464 1.525 1.599 1.683 1.751 1.881 1.962
 2.15  2.226 2.371 2.453 2.619 2.754 2.839 2.995 3.059 3.343 3.381 3.616
 3.677 3.871 4.197 4.506 4.986 5.134 5.521 6.394]
10 9
[0.15221668 0.39322708 0.39400861 0.48714745 0.55239843]
eigval are [0.16  0.4   0.401 0.499 0.582 0.613 0.667 0.778 0.856 0.883 0.937 1.002
 1.022 1.057 1.103 1.213 1.411 1.483 1.545 1.612 1.682 1.762 1.889 1.968
 2.165 2.252 2.359 2.453 2.634 2.754 2.847 2.996 3.062 3.358 3.406 3.616
 3.704 3.874 4.192 4.489 4.991 5.134 5.533 6.411]
10 9
[0.16027576 0.39965332 0.40085693 0.49929981 0.58239575]
109
eigval are [0.153 0.395 0.396 0.491 0.554 0.6   0.622 0.752 0.783 0.853 0.917 1.
 1.009 1.046 1.086 1.214 1.399 1.465 1.527 1.601 1.685 1.754 1.883 1.965
 2.153 2.23  2.373 2.456 2.623 2.758 2.842 2.998 3.063 3.347 3.386 3.623
 3.684 3.878 4.206 4.515

10 9
[0.16339174 0.40867988 0.41014619 0.50864886 0.59171357]
120
eigval are [0.155 0.404 0.404 0.5   0.562 0.611 0.631 0.764 0.795 0.868 0.933 1.011
 1.027 1.055 1.105 1.233 1.42  1.489 1.543 1.624 1.702 1.782 1.911 1.999
 2.189 2.26  2.401 2.484 2.673 2.801 2.877 3.022 3.104 3.4   3.441 3.678
 3.744 3.956 4.306 4.603 5.102 5.272 5.642 6.563]
10 9
[0.15476699 0.40401027 0.40421097 0.4995475  0.56199991]
eigval are [0.163 0.41  0.41  0.51  0.593 0.629 0.68  0.791 0.874 0.898 0.955 1.005
 1.042 1.079 1.125 1.237 1.435 1.505 1.562 1.636 1.701 1.795 1.921 2.006
 2.202 2.289 2.39  2.484 2.688 2.8   2.884 3.025 3.106 3.413 3.468 3.677
 3.779 3.959 4.301 4.587 5.105 5.271 5.654 6.579]
10 9
[0.1633037  0.41004726 0.41029505 0.51035518 0.59331837]
121
eigval are [0.156 0.405 0.406 0.502 0.563 0.613 0.632 0.765 0.796 0.871 0.935 1.012
 1.03  1.058 1.107 1.236 1.421 1.49  1.545 1.627 1.704 1.785 1.913 2.002
 2.192 2.263 2.403 2.487 2.677 2.805 2.88  3.026 3.108 3.405 3.446 3.686
 3.751 3.963 4.3

10 9
[0.1660723  0.41807502 0.41971837 0.51874889 0.60103995]
132
eigval are [0.158 0.414 0.415 0.514 0.571 0.625 0.642 0.778 0.807 0.889 0.952 1.023
 1.048 1.075 1.125 1.256 1.44  1.509 1.561 1.649 1.721 1.812 1.938 2.034
 2.225 2.293 2.429 2.515 2.722 2.846 2.916 3.05  3.148 3.453 3.496 3.742
 3.814 4.037 4.409 4.696 5.208 5.402 5.755 6.72 ]
10 9
[0.15809401 0.4141251  0.41541764 0.51359516 0.57071392]
eigval are [0.168 0.42  0.421 0.525 0.605 0.646 0.693 0.803 0.893 0.914 0.979 1.013
 1.064 1.103 1.145 1.263 1.455 1.525 1.579 1.66  1.72  1.827 1.949 2.041
 2.238 2.324 2.419 2.514 2.737 2.844 2.923 3.054 3.149 3.464 3.524 3.742
 3.855 4.039 4.405 4.68  5.214 5.401 5.769 6.738]
10 9
[0.16844004 0.42022994 0.42112404 0.52545416 0.60451482]
133
eigval are [0.158 0.415 0.416 0.512 0.572 0.63  0.641 0.782 0.808 0.89  0.953 1.023
 1.05  1.077 1.127 1.261 1.441 1.51  1.562 1.651 1.722 1.814 1.941 2.036
 2.228 2.297 2.431 2.517 2.727 2.849 2.919 3.052 3.151 3.457 3.501 3.747
 3.821 4.042 4.4

10 9
[0.16833053 0.42690874 0.4277041  0.52831753 0.61046709]
144
eigval are [0.158 0.42  0.422 0.513 0.577 0.64  0.648 0.794 0.818 0.899 0.965 1.02
 1.065 1.086 1.142 1.282 1.458 1.527 1.578 1.671 1.738 1.839 1.964 2.066
 2.26  2.324 2.454 2.545 2.769 2.887 2.955 3.073 3.19  3.504 3.548 3.798
 3.882 4.112 4.505 4.782 5.306 5.527 5.863 6.872]
10 9
[0.15795154 0.4202144  0.42180098 0.51301173 0.57673859]
eigval are [0.169 0.428 0.428 0.529 0.611 0.656 0.704 0.814 0.906 0.927 0.993 1.007
 1.08  1.121 1.164 1.288 1.475 1.544 1.596 1.679 1.738 1.855 1.975 2.074
 2.272 2.355 2.445 2.544 2.784 2.885 2.962 3.077 3.192 3.515 3.576 3.799
 3.923 4.115 4.502 4.766 5.311 5.526 5.876 6.888]
10 9
[0.16856016 0.42766632 0.42838531 0.52907302 0.61114005]
145
eigval are [0.158 0.421 0.423 0.514 0.577 0.641 0.649 0.796 0.819 0.9   0.966 1.02
 1.066 1.088 1.144 1.285 1.46  1.528 1.58  1.673 1.739 1.842 1.966 2.068
 2.263 2.327 2.456 2.547 2.773 2.89  2.958 3.075 3.194 3.508 3.553 3.803
 3.888 4.118 4.513

10 9
[0.1707324  0.43531954 0.43617411 0.53609938 0.61828435]
156
eigval are [0.16  0.429 0.43  0.52  0.583 0.65  0.662 0.809 0.829 0.915 0.98  1.026
 1.082 1.105 1.161 1.304 1.477 1.545 1.596 1.692 1.755 1.866 1.988 2.096
 2.294 2.354 2.478 2.575 2.812 2.925 2.995 3.098 3.232 3.552 3.596 3.856
 3.946 4.186 4.6   4.865 5.402 5.647 5.967 7.018]
10 9
[0.16029954 0.42922885 0.4303697  0.52027813 0.58348029]
eigval are [0.171 0.435 0.438 0.535 0.618 0.667 0.714 0.825 0.919 0.942 1.007 1.011
 1.097 1.14  1.185 1.309 1.494 1.565 1.615 1.699 1.756 1.883 1.999 2.105
 2.307 2.385 2.47  2.574 2.827 2.923 3.    3.1   3.235 3.564 3.622 3.856
 3.987 4.19  4.597 4.849 5.408 5.647 5.98  7.033]
10 9
[0.1712266  0.435202   0.43765828 0.53531244 0.61753366]
157
eigval are [0.161 0.431 0.431 0.523 0.584 0.653 0.662 0.808 0.83  0.917 0.982 1.029
 1.084 1.108 1.163 1.304 1.478 1.547 1.598 1.694 1.757 1.868 1.989 2.099
 2.297 2.356 2.48  2.577 2.815 2.928 2.997 3.1   3.235 3.556 3.599 3.862
 3.951 4.192 4.6

10 9
[0.17352452 0.44233598 0.44496891 0.54146484 0.62364198]
168
eigval are [0.162 0.436 0.438 0.523 0.588 0.657 0.677 0.821 0.839 0.927 0.993 1.028
 1.097 1.122 1.179 1.325 1.494 1.561 1.615 1.712 1.772 1.891 2.01  2.126
 2.327 2.382 2.501 2.604 2.851 2.961 3.034 3.121 3.272 3.599 3.641 3.911
 4.007 4.257 4.69  4.945 5.494 5.763 6.068 7.157]
10 9
[0.1616171  0.43646039 0.43834276 0.52325741 0.58809334]
eigval are [0.174 0.443 0.445 0.542 0.624 0.677 0.726 0.835 0.933 0.956 1.011 1.026
 1.113 1.158 1.202 1.333 1.512 1.58  1.632 1.716 1.775 1.909 2.022 2.135
 2.338 2.415 2.494 2.603 2.867 2.96  3.038 3.124 3.276 3.609 3.667 3.913
 4.051 4.26  4.688 4.929 5.502 5.762 6.081 7.173]
10 9
[0.17372401 0.44315866 0.44549766 0.54236371 0.62440552]
169
eigval are [0.165 0.44  0.441 0.532 0.592 0.666 0.678 0.822 0.84  0.935 0.999 1.038
 1.103 1.128 1.18  1.327 1.495 1.563 1.616 1.714 1.774 1.893 2.011 2.128
 2.33  2.385 2.503 2.607 2.853 2.965 3.037 3.125 3.275 3.602 3.644 3.922
 4.015 4.262 4.6

10 9
[0.17577252 0.45065225 0.4523225  0.54923126 0.62992087]
180
eigval are [0.164 0.444 0.446 0.528 0.597 0.663 0.696 0.838 0.849 0.94  1.006 1.031
 1.112 1.141 1.197 1.348 1.51  1.576 1.633 1.73  1.789 1.914 2.031 2.152
 2.358 2.411 2.523 2.633 2.887 2.996 3.073 3.144 3.311 3.641 3.684 3.967
 4.069 4.323 4.776 5.021 5.585 5.874 6.166 7.294]
10 9
[0.16369957 0.44436398 0.44624257 0.52805679 0.5969727 ]
eigval are [0.176 0.451 0.454 0.548 0.632 0.686 0.737 0.845 0.945 0.971 1.012 1.041
 1.127 1.176 1.221 1.356 1.529 1.596 1.649 1.731 1.793 1.933 2.044 2.163
 2.368 2.444 2.517 2.632 2.903 2.995 3.075 3.149 3.316 3.651 3.709 3.971
 4.114 4.326 4.775 5.005 5.594 5.873 6.179 7.309]
10 9
[0.17627891 0.45067116 0.45355478 0.54847864 0.63152384]
181
eigval are [0.165 0.445 0.447 0.53  0.598 0.666 0.698 0.84  0.85  0.941 1.008 1.032
 1.114 1.141 1.198 1.351 1.511 1.577 1.634 1.731 1.79  1.917 2.033 2.155
 2.36  2.413 2.525 2.636 2.889 2.998 3.076 3.147 3.314 3.644 3.688 3.973
 4.075 4.329 4.7

10 9
[0.17821098 0.45712215 0.46015413 0.55378647 0.63772548]
192
eigval are [0.169 0.455 0.456 0.542 0.609 0.682 0.71  0.852 0.86  0.958 1.024 1.046
 1.132 1.159 1.213 1.37  1.526 1.59  1.65  1.747 1.806 1.938 2.051 2.18
 2.387 2.438 2.545 2.662 2.919 3.03  3.109 3.171 3.349 3.682 3.727 4.027
 4.13  4.388 4.862 5.095 5.679 5.981 6.261 7.424]
10 9
[0.16911604 0.45473218 0.45605402 0.54204739 0.60859382]
eigval are [0.178 0.458 0.461 0.555 0.638 0.694 0.747 0.854 0.958 0.983 1.016 1.055
 1.142 1.192 1.238 1.377 1.546 1.61  1.668 1.745 1.811 1.956 2.064 2.19
 2.397 2.472 2.539 2.661 2.936 3.029 3.108 3.174 3.356 3.691 3.751 4.026
 4.171 4.392 4.859 5.078 5.68  5.98  6.273 7.438]
10 9
[0.17779147 0.45842474 0.46082944 0.55460309 0.63840726]
193
eigval are [0.169 0.456 0.457 0.543 0.61  0.683 0.709 0.852 0.86  0.959 1.025 1.046
 1.133 1.161 1.215 1.371 1.527 1.592 1.652 1.748 1.807 1.94  2.052 2.182
 2.39  2.44  2.547 2.665 2.921 3.033 3.112 3.173 3.353 3.685 3.73  4.031
 4.135 4.394 4.868

In [7]:
T = 200
i = 2
dirpath = '/Users/jiayiwu/experiment/bio/bio_mec_2019' + '/'
opath = dirpath + '/plots%d_%d/'%(T,i)
if not os.path.exists(opath): os.mkdir(opath)
tpath = dirpath + '/switch_goal%d_%d/'%(T,i)
if not os.path.exists(tpath): os.mkdir(tpath)